# Generated by Django 4.2 on 2025-09-09 07:40

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address_type', models.CharField(blank=True, choices=[('current', 'Current'), ('permanent', 'Permanent')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='area',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='parent_contact_number',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='state',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='area',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_contact_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.RemoveField(
            model_name='student',
            name='street_name',
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='emergency_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='identification',
            field=models.CharField(blank=True, help_text='Aadhaar, Passport, SSN, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='photograph',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='identification',
            field=models.CharField(blank=True, help_text='Aadhaar, Passport, SSN, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='student',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='current_address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.address'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='parent_guardian',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.parentguardian'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='permanent_address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.address'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='students.address'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.parentguardian'),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_students', to='students.address'),
        ),
    ]
