# Generated by Django 4.2 on 2025-09-09 16:39

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_country_state_city_alter_address_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='parent_guardian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_guardian',
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='same_as_current_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='same_as_current_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Bhubaneswar', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='OD', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='Unknown', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='Unknown', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='ParentGuardian',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='father',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'relationship': 'father'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.parent'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='mother',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'relationship': 'mother'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='father',
            field=models.OneToOneField(blank=True, limit_choices_to={'relationship': 'father'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_of', to='students.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother',
            field=models.OneToOneField(blank=True, limit_choices_to={'relationship': 'mother'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_of', to='students.parent'),
        ),
    ]
