# Generated by Django 4.2 on 2025-09-26 15:49

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        ('students', '0004_parent_remove_state_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstudent',
            old_name='emergency_contact_name',
            new_name='current_area',
        ),
        migrations.RenameField(
            model_name='historicalstudent',
            old_name='emergency_contact_relationship',
            new_name='father_first_name',
        ),
        migrations.RenameField(
            model_name='historicalstudent',
            old_name='nationality',
            new_name='father_last_name',
        ),
        migrations.RenameField(
            model_name='historicalstudent',
            old_name='emergency_contact_phone',
            new_name='father_phone',
        ),
        migrations.RenameField(
            model_name='historicalstudent',
            old_name='same_as_current_address',
            new_name='permanent_same_as_current',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='emergency_contact_name',
            new_name='current_area',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='emergency_contact_relationship',
            new_name='father_first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='nationality',
            new_name='father_last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='emergency_contact_phone',
            new_name='father_phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='same_as_current_address',
            new_name='permanent_same_as_current',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='father',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='student',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='current_city',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='current_region', chained_model_field='region', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='current_country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='current_pin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='current_region',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='current_country', chained_model_field='country', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='current_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='mother_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='permanent_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='permanent_city',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='permanent_region', chained_model_field='region', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='permanent_country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='permanent_pin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='permanent_region',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='permanent_country', chained_model_field='country', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='permanent_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_city',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='current_region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_pin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_region',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='current_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_city',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='permanent_region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_pin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_region',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='permanent_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
