--
-- PostgreSQL database dump
--

\restrict x1srOOsoRp1pLiQZys4tHhjvHV6PzCXH1qXKTYoBWnVvctt0FHb62yEiVhzqFml

-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 15.14 (Debian 15.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: academics_course; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.academics_course (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    created timestamp with time zone NOT NULL
);


ALTER TABLE public.academics_course OWNER TO scms_admin;

--
-- Name: academics_course_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.academics_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academics_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: academics_lesson; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.academics_lesson (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    "position" smallint,
    is_done boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    CONSTRAINT academics_lesson_position_check CHECK (("position" >= 0))
);


ALTER TABLE public.academics_lesson OWNER TO scms_admin;

--
-- Name: academics_lesson_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.academics_lesson ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academics_lesson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: academics_lessonchecklistitem; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.academics_lessonchecklistitem (
    id bigint NOT NULL,
    text character varying(255) NOT NULL,
    completed boolean NOT NULL,
    "position" smallint,
    lesson_id bigint NOT NULL,
    CONSTRAINT academics_lessonchecklistitem_position_check CHECK (("position" >= 0))
);


ALTER TABLE public.academics_lessonchecklistitem OWNER TO scms_admin;

--
-- Name: academics_lessonchecklistitem_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.academics_lessonchecklistitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academics_lessonchecklistitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO scms_admin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO scms_admin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO scms_admin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO scms_admin;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO scms_admin;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO scms_admin;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO scms_admin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO scms_admin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO scms_admin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: scms_admin
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: scms_admin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO scms_admin;

--
-- Data for Name: academics_course; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.academics_course (id, title, description, created) FROM stdin;
1	Introduction to Computer Science	Fundamentals of computing, algorithms and problem solving.	2025-10-13 16:49:44.001434+00
2	Programming in Python	Core Python language features and practical programming.	2025-10-13 16:49:44.064998+00
3	Data Structures & Algorithms	Common data structures and algorithm design techniques.	2025-10-13 16:49:44.071344+00
4	Databases & SQL	Relational databases, SQL and basic database design.	2025-10-13 16:49:44.075639+00
5	Web Development with Django	Build web apps with Django: models, views, templates and auth.	2025-10-13 16:49:44.078263+00
6	Operating Systems & Networking	Intro to OS concepts and fundamental networking principles.	2025-10-13 16:49:44.080938+00
7	Software Engineering Practices	Design, testing and team practices for reliable software.	2025-10-13 16:49:44.083842+00
8	Microeconomics	Foundations of microeconomics: consumers, firms and markets.	2025-10-13 16:49:44.086577+00
9	Macroeconomics	Aggregate economy: GDP, inflation, unemployment and policy.	2025-10-13 16:49:44.089183+00
10	Intro to Econometrics	Basics of data analysis and causal inference in economics.	2025-10-13 16:49:44.091784+00
\.


--
-- Data for Name: academics_lesson; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.academics_lesson (id, title, content, "position", is_done, created, course_id) FROM stdin;
1	What is Computer Science?	Lesson: What is Computer Science?\n\nIntroduction to Computer Science - detailed content.	1	f	2025-10-13 16:49:44.034032+00	1
2	Algorithms & Pseudocode	Lesson: Algorithms & Pseudocode\n\nIntroduction to Computer Science - detailed content.	2	f	2025-10-13 16:49:44.057382+00	1
3	Basic Data Types	Lesson: Basic Data Types\n\nIntroduction to Computer Science - detailed content.	3	f	2025-10-13 16:49:44.058504+00	1
4	Control Flow	Lesson: Control Flow\n\nIntroduction to Computer Science - detailed content.	4	f	2025-10-13 16:49:44.059448+00	1
5	Functions and Procedures	Lesson: Functions and Procedures\n\nIntroduction to Computer Science - detailed content.	5	f	2025-10-13 16:49:44.060305+00	1
6	Basic Data Structures	Lesson: Basic Data Structures\n\nIntroduction to Computer Science - detailed content.	6	f	2025-10-13 16:49:44.061042+00	1
7	Complexity & Big-O	Lesson: Complexity & Big-O\n\nIntroduction to Computer Science - detailed content.	7	f	2025-10-13 16:49:44.061815+00	1
8	Debugging Techniques	Lesson: Debugging Techniques\n\nIntroduction to Computer Science - detailed content.	8	f	2025-10-13 16:49:44.062541+00	1
9	Version Control (git)	Lesson: Version Control (git)\n\nIntroduction to Computer Science - detailed content.	9	f	2025-10-13 16:49:44.063323+00	1
10	Next Steps & Resources	Lesson: Next Steps & Resources\n\nIntroduction to Computer Science - detailed content.	10	f	2025-10-13 16:49:44.064217+00	1
11	Python setup & REPL	Lesson: Python setup & REPL\n\nProgramming in Python - detailed content.	1	f	2025-10-13 16:49:44.065724+00	2
12	Variables and Types	Lesson: Variables and Types\n\nProgramming in Python - detailed content.	2	f	2025-10-13 16:49:44.06642+00	2
13	Control Flow in Python	Lesson: Control Flow in Python\n\nProgramming in Python - detailed content.	3	f	2025-10-13 16:49:44.067064+00	2
14	Functions and Modules	Lesson: Functions and Modules\n\nProgramming in Python - detailed content.	4	f	2025-10-13 16:49:44.067694+00	2
15	Data Structures: lists & tuples	Lesson: Data Structures: lists & tuples\n\nProgramming in Python - detailed content.	5	f	2025-10-13 16:49:44.068289+00	2
16	Dictionaries & Sets	Lesson: Dictionaries & Sets\n\nProgramming in Python - detailed content.	6	f	2025-10-13 16:49:44.068747+00	2
17	File I/O	Lesson: File I/O\n\nProgramming in Python - detailed content.	7	f	2025-10-13 16:49:44.069542+00	2
18	Error Handling	Lesson: Error Handling\n\nProgramming in Python - detailed content.	8	f	2025-10-13 16:49:44.070029+00	2
19	Iterators & Generators	Lesson: Iterators & Generators\n\nProgramming in Python - detailed content.	9	f	2025-10-13 16:49:44.070482+00	2
20	Virtualenv & Packaging	Lesson: Virtualenv & Packaging\n\nProgramming in Python - detailed content.	10	f	2025-10-13 16:49:44.070934+00	2
21	Arrays and Linked Lists	Lesson: Arrays and Linked Lists\n\nData Structures & Algorithms - detailed content.	1	f	2025-10-13 16:49:44.07167+00	3
22	Stacks and Queues	Lesson: Stacks and Queues\n\nData Structures & Algorithms - detailed content.	2	f	2025-10-13 16:49:44.072313+00	3
23	Trees and Binary Trees	Lesson: Trees and Binary Trees\n\nData Structures & Algorithms - detailed content.	3	f	2025-10-13 16:49:44.072819+00	3
24	Graphs Basics	Lesson: Graphs Basics\n\nData Structures & Algorithms - detailed content.	4	f	2025-10-13 16:49:44.073268+00	3
25	Searching & Sorting	Lesson: Searching & Sorting\n\nData Structures & Algorithms - detailed content.	5	f	2025-10-13 16:49:44.073834+00	3
26	Hashing and Dictionaries	Lesson: Hashing and Dictionaries\n\nData Structures & Algorithms - detailed content.	6	f	2025-10-13 16:49:44.074279+00	3
27	Recursion & Divide & Conquer	Lesson: Recursion & Divide & Conquer\n\nData Structures & Algorithms - detailed content.	7	f	2025-10-13 16:49:44.074541+00	3
28	Greedy Algorithms	Lesson: Greedy Algorithms\n\nData Structures & Algorithms - detailed content.	8	f	2025-10-13 16:49:44.074791+00	3
29	Dynamic Programming	Lesson: Dynamic Programming\n\nData Structures & Algorithms - detailed content.	9	f	2025-10-13 16:49:44.075062+00	3
30	Algorithm Analysis	Lesson: Algorithm Analysis\n\nData Structures & Algorithms - detailed content.	10	f	2025-10-13 16:49:44.075359+00	3
31	Introduction to Databases	Lesson: Introduction to Databases\n\nDatabases & SQL - detailed content.	1	f	2025-10-13 16:49:44.075881+00	4
32	Basic SELECT queries	Lesson: Basic SELECT queries\n\nDatabases & SQL - detailed content.	2	f	2025-10-13 16:49:44.076125+00	4
33	Filtering and Sorting	Lesson: Filtering and Sorting\n\nDatabases & SQL - detailed content.	3	f	2025-10-13 16:49:44.076363+00	4
34	JOINs	Lesson: JOINs\n\nDatabases & SQL - detailed content.	4	f	2025-10-13 16:49:44.076597+00	4
35	Aggregations & GROUP BY	Lesson: Aggregations & GROUP BY\n\nDatabases & SQL - detailed content.	5	f	2025-10-13 16:49:44.076838+00	4
36	Indexes and Performance	Lesson: Indexes and Performance\n\nDatabases & SQL - detailed content.	6	f	2025-10-13 16:49:44.077072+00	4
37	Transactions & Concurrency	Lesson: Transactions & Concurrency\n\nDatabases & SQL - detailed content.	7	f	2025-10-13 16:49:44.077313+00	4
38	Schema Design	Lesson: Schema Design\n\nDatabases & SQL - detailed content.	8	f	2025-10-13 16:49:44.077569+00	4
39	ORM Basics	Lesson: ORM Basics\n\nDatabases & SQL - detailed content.	9	f	2025-10-13 16:49:44.077807+00	4
40	Backups & Migrations	Lesson: Backups & Migrations\n\nDatabases & SQL - detailed content.	10	f	2025-10-13 16:49:44.078041+00	4
41	Django project setup	Lesson: Django project setup\n\nWeb Development with Django - detailed content.	1	f	2025-10-13 16:49:44.078499+00	5
42	Models and Migrations	Lesson: Models and Migrations\n\nWeb Development with Django - detailed content.	2	f	2025-10-13 16:49:44.078751+00	5
43	Admin Customisation	Lesson: Admin Customisation\n\nWeb Development with Django - detailed content.	3	f	2025-10-13 16:49:44.079014+00	5
44	Views and URL routing	Lesson: Views and URL routing\n\nWeb Development with Django - detailed content.	4	f	2025-10-13 16:49:44.07927+00	5
45	Templates and static files	Lesson: Templates and static files\n\nWeb Development with Django - detailed content.	5	f	2025-10-13 16:49:44.079522+00	5
46	Forms and validation	Lesson: Forms and validation\n\nWeb Development with Django - detailed content.	6	f	2025-10-13 16:49:44.079758+00	5
47	Authentication & Permissions	Lesson: Authentication & Permissions\n\nWeb Development with Django - detailed content.	7	f	2025-10-13 16:49:44.079991+00	5
48	File uploads	Lesson: File uploads\n\nWeb Development with Django - detailed content.	8	f	2025-10-13 16:49:44.080226+00	5
49	Testing Django apps	Lesson: Testing Django apps\n\nWeb Development with Django - detailed content.	9	f	2025-10-13 16:49:44.080473+00	5
50	Deployment basics	Lesson: Deployment basics\n\nWeb Development with Django - detailed content.	10	f	2025-10-13 16:49:44.080713+00	5
51	Processes and Threads	Lesson: Processes and Threads\n\nOperating Systems & Networking - detailed content.	1	f	2025-10-13 16:49:44.081167+00	6
52	Memory Management	Lesson: Memory Management\n\nOperating Systems & Networking - detailed content.	2	f	2025-10-13 16:49:44.081427+00	6
53	File Systems	Lesson: File Systems\n\nOperating Systems & Networking - detailed content.	3	f	2025-10-13 16:49:44.081687+00	6
54	I/O and Drivers	Lesson: I/O and Drivers\n\nOperating Systems & Networking - detailed content.	4	f	2025-10-13 16:49:44.082104+00	6
55	Concurrency basics	Lesson: Concurrency basics\n\nOperating Systems & Networking - detailed content.	5	f	2025-10-13 16:49:44.082396+00	6
56	Networking models (OSI/TCP/IP)	Lesson: Networking models (OSI/TCP/IP)\n\nOperating Systems & Networking - detailed content.	6	f	2025-10-13 16:49:44.082652+00	6
57	Sockets and TCP/UDP	Lesson: Sockets and TCP/UDP\n\nOperating Systems & Networking - detailed content.	7	f	2025-10-13 16:49:44.082902+00	6
58	Network troubleshooting	Lesson: Network troubleshooting\n\nOperating Systems & Networking - detailed content.	8	f	2025-10-13 16:49:44.083146+00	6
59	Security basics	Lesson: Security basics\n\nOperating Systems & Networking - detailed content.	9	f	2025-10-13 16:49:44.083383+00	6
60	System monitoring	Lesson: System monitoring\n\nOperating Systems & Networking - detailed content.	10	f	2025-10-13 16:49:44.083618+00	6
61	Software development lifecycle	Lesson: Software development lifecycle\n\nSoftware Engineering Practices - detailed content.	1	f	2025-10-13 16:49:44.084086+00	7
62	Design patterns overview	Lesson: Design patterns overview\n\nSoftware Engineering Practices - detailed content.	2	f	2025-10-13 16:49:44.084337+00	7
63	Modular design	Lesson: Modular design\n\nSoftware Engineering Practices - detailed content.	3	f	2025-10-13 16:49:44.084578+00	7
64	Unit testing	Lesson: Unit testing\n\nSoftware Engineering Practices - detailed content.	4	f	2025-10-13 16:49:44.084813+00	7
65	Integration testing	Lesson: Integration testing\n\nSoftware Engineering Practices - detailed content.	5	f	2025-10-13 16:49:44.085088+00	7
66	CI/CD basics	Lesson: CI/CD basics\n\nSoftware Engineering Practices - detailed content.	6	f	2025-10-13 16:49:44.085334+00	7
67	Code review best practices	Lesson: Code review best practices\n\nSoftware Engineering Practices - detailed content.	7	f	2025-10-13 16:49:44.085622+00	7
68	Documentation	Lesson: Documentation\n\nSoftware Engineering Practices - detailed content.	8	f	2025-10-13 16:49:44.085878+00	7
69	Project management basics	Lesson: Project management basics\n\nSoftware Engineering Practices - detailed content.	9	f	2025-10-13 16:49:44.086118+00	7
70	Maintenance and refactoring	Lesson: Maintenance and refactoring\n\nSoftware Engineering Practices - detailed content.	10	f	2025-10-13 16:49:44.086352+00	7
71	Supply and Demand	Lesson: Supply and Demand\n\nMicroeconomics - detailed content.	1	f	2025-10-13 16:49:44.086804+00	8
72	Elasticity	Lesson: Elasticity\n\nMicroeconomics - detailed content.	2	f	2025-10-13 16:49:44.087045+00	8
73	Consumer Choice	Lesson: Consumer Choice\n\nMicroeconomics - detailed content.	3	f	2025-10-13 16:49:44.087287+00	8
74	Production & Costs	Lesson: Production & Costs\n\nMicroeconomics - detailed content.	4	f	2025-10-13 16:49:44.087525+00	8
75	Perfect Competition	Lesson: Perfect Competition\n\nMicroeconomics - detailed content.	5	f	2025-10-13 16:49:44.08776+00	8
76	Monopoly & Market Power	Lesson: Monopoly & Market Power\n\nMicroeconomics - detailed content.	6	f	2025-10-13 16:49:44.087996+00	8
77	Oligopoly basics	Lesson: Oligopoly basics\n\nMicroeconomics - detailed content.	7	f	2025-10-13 16:49:44.08823+00	8
78	Market Failures	Lesson: Market Failures\n\nMicroeconomics - detailed content.	8	f	2025-10-13 16:49:44.088471+00	8
79	Externalities	Lesson: Externalities\n\nMicroeconomics - detailed content.	9	f	2025-10-13 16:49:44.08872+00	8
80	Public Policy & Regulation	Lesson: Public Policy & Regulation\n\nMicroeconomics - detailed content.	10	f	2025-10-13 16:49:44.08896+00	8
81	Measuring the Economy (GDP)	Lesson: Measuring the Economy (GDP)\n\nMacroeconomics - detailed content.	1	f	2025-10-13 16:49:44.089425+00	9
82	Unemployment & Labor Markets	Lesson: Unemployment & Labor Markets\n\nMacroeconomics - detailed content.	2	f	2025-10-13 16:49:44.089679+00	9
83	Inflation & Price Indexes	Lesson: Inflation & Price Indexes\n\nMacroeconomics - detailed content.	3	f	2025-10-13 16:49:44.089913+00	9
84	Aggregate Demand & Supply	Lesson: Aggregate Demand & Supply\n\nMacroeconomics - detailed content.	4	f	2025-10-13 16:49:44.090153+00	9
85	Fiscal Policy	Lesson: Fiscal Policy\n\nMacroeconomics - detailed content.	5	f	2025-10-13 16:49:44.090389+00	9
86	Monetary Policy	Lesson: Monetary Policy\n\nMacroeconomics - detailed content.	6	f	2025-10-13 16:49:44.090624+00	9
87	Economic Growth	Lesson: Economic Growth\n\nMacroeconomics - detailed content.	7	f	2025-10-13 16:49:44.090858+00	9
88	Business Cycles	Lesson: Business Cycles\n\nMacroeconomics - detailed content.	8	f	2025-10-13 16:49:44.09109+00	9
89	Open Economy / Exchange Rates	Lesson: Open Economy / Exchange Rates\n\nMacroeconomics - detailed content.	9	f	2025-10-13 16:49:44.091319+00	9
90	Policy Tradeoffs	Lesson: Policy Tradeoffs\n\nMacroeconomics - detailed content.	10	f	2025-10-13 16:49:44.091562+00	9
91	Data types & sources	Lesson: Data types & sources\n\nIntro to Econometrics - detailed content.	0	f	2025-10-13 16:49:44.092023+00	10
92	Statistical foundations	Lesson: Statistical foundations\n\nIntro to Econometrics - detailed content.	1	f	2025-10-13 16:49:44.092279+00	10
93	Simple linear regression	Lesson: Simple linear regression\n\nIntro to Econometrics - detailed content.	2	f	2025-10-13 16:49:44.092526+00	10
94	Multiple regression	Lesson: Multiple regression\n\nIntro to Econometrics - detailed content.	3	f	2025-10-13 16:49:44.092763+00	10
95	Hypothesis testing	Lesson: Hypothesis testing\n\nIntro to Econometrics - detailed content.	4	f	2025-10-13 16:49:44.093005+00	10
96	Model specification	Lesson: Model specification\n\nIntro to Econometrics - detailed content.	5	f	2025-10-13 16:49:44.093354+00	10
97	Heteroskedasticity & remedies	Lesson: Heteroskedasticity & remedies\n\nIntro to Econometrics - detailed content.	6	f	2025-10-13 16:49:44.093662+00	10
98	Instrumental variables (intro)	Lesson: Instrumental variables (intro)\n\nIntro to Econometrics - detailed content.	7	f	2025-10-13 16:49:44.093914+00	10
99	Panel data basics	Lesson: Panel data basics\n\nIntro to Econometrics - detailed content.	8	f	2025-10-13 16:49:44.094155+00	10
100	Interpreting results	Lesson: Interpreting results\n\nIntro to Econometrics - detailed content.	9	f	2025-10-13 16:49:44.094453+00	10
\.


--
-- Data for Name: academics_lessonchecklistitem; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.academics_lessonchecklistitem (id, text, completed, "position", lesson_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.auth_group (id, name) FROM stdin;
1	Teachers
2	Students
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add content type	1	add_contenttype
2	Can change content type	1	change_contenttype
3	Can delete content type	1	delete_contenttype
4	Can view content type	1	view_contenttype
5	Can add log entry	2	add_logentry
6	Can change log entry	2	change_logentry
7	Can delete log entry	2	delete_logentry
8	Can view log entry	2	view_logentry
9	Can add permission	3	add_permission
10	Can change permission	3	change_permission
11	Can delete permission	3	delete_permission
12	Can view permission	3	view_permission
13	Can add group	4	add_group
14	Can change group	4	change_group
15	Can delete group	4	delete_group
16	Can view group	4	view_group
17	Can add user	5	add_user
18	Can change user	5	change_user
19	Can delete user	5	delete_user
20	Can view user	5	view_user
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add course	7	add_course
26	Can change course	7	change_course
27	Can delete course	7	delete_course
28	Can view course	7	view_course
29	Can add lesson	8	add_lesson
30	Can change lesson	8	change_lesson
31	Can delete lesson	8	delete_lesson
32	Can view lesson	8	view_lesson
33	Can add lesson checklist item	9	add_lessonchecklistitem
34	Can change lesson checklist item	9	change_lessonchecklistitem
35	Can delete lesson checklist item	9	delete_lessonchecklistitem
36	Can view lesson checklist item	9	view_lessonchecklistitem
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$600000$ki1BRIXy8WArtCRZvPx1mP$Fiv3Qvpw49Dgsx4/Cof27eNw08fhUQLgCfSvNIC7aSk=	2025-10-13 16:19:47.784545+00	t	admin				t	t	2025-10-13 16:19:37.448181+00
2	pbkdf2_sha256$600000$fPBdCmVb5INZ7pOmTjpQc3$ehHORN57Grcoyz9Qe0Hbp2gcJUaO2RmO4hpwm/8CMBc=	\N	f	ranveerdevan	Ranveer	Devan	ranveerdevan@hotmail.com	t	t	2025-10-13 17:40:33.82527+00
3	pbkdf2_sha256$600000$4UtWEmGIH63bW0MkJjd9TF$O1Ch/Rjcvs7J06C72l7yRSRsAWILgl8/2zDYzaE9mAE=	\N	f	bhavikadash	Bhavika	Dash	bhavikadash@hotmail.com	t	t	2025-10-13 17:40:34.068942+00
4	pbkdf2_sha256$600000$wWzCvShCYNtEUAyOUrsuiH$2ea479AnjPm5Q4s+NzOYSnbiXrBcBQ50gABh4UdyXPQ=	\N	f	dalajapurohit	Dalaja	Purohit	dalajapurohit@gmail.com	t	t	2025-10-13 17:40:34.287605+00
5	pbkdf2_sha256$600000$wbL5yrRSlX7OX2IwDlkzRU$lEOMgO//66Jtmoiw4blpJ9eRoyA8MJSVLuoyg99Pr5E=	\N	f	jyotipingle	Jyoti	Pingle	jyotipingle@gmail.com	t	t	2025-10-13 17:40:34.517396+00
6	pbkdf2_sha256$600000$VhoS6ZpUJJCwUqpdbRdZls$/O6UP5pIe7UnHstKx7QMWZRtGMIfgrWWCifC2L+OG3k=	\N	f	jagdishgade	Jagdish	Gade	jagdishgade@gmail.com	t	t	2025-10-13 17:40:34.746+00
7	pbkdf2_sha256$600000$IwPATEuyKVy8tuS9f1rtmc$o8GC2QiUI9S8pozWWhHr9HXLqtpMrGvIW3vmAiMHO5g=	\N	f	lipikamuni	Lipika	Muni	lipikamuni@yahoo.in	t	t	2025-10-13 17:40:34.965013+00
8	pbkdf2_sha256$600000$1IerZDfAMXNOyADWaN5oOH$r8zI8Ei504wNHBa2gAwRXI3d0UyepnYymEVjgrrGZgA=	\N	f	indrajitdube	Indrajit	Dube	indrajitdube@yahoo.in	t	t	2025-10-13 17:40:35.193176+00
9	pbkdf2_sha256$600000$l2bxpIY7UoeRbBE1Ss1Aha$fMYhLOJ3goLHKjM4us4uwVkt1OAkrRqSR9Ws5u0Q8GE=	\N	f	zayanjaggi	Zayan	Jaggi	zayanjaggi@gmail.com	t	t	2025-10-13 17:40:35.422362+00
10	pbkdf2_sha256$600000$cSwsrc6D9QUKsKs2FCaYZQ$Do31lwGTln/YNwZxt2qIjXh1Rrb8P0Y0uzvQ1AGSy40=	\N	f	farisbajaj	Faris	Bajaj	farisbajaj@outlook.com	t	t	2025-10-13 17:40:35.651699+00
11	pbkdf2_sha256$600000$vjPmSn9ZFnwPAyQMRQaAx1$nz01xuuWE3g97sk28Gazh1O6wN8k0+YOB0WcqG8gfcc=	\N	f	ijayasubramanian	Ijaya	Subramanian	ijayasubramanian@outlook.com	t	t	2025-10-13 17:40:35.880638+00
12	pbkdf2_sha256$600000$gXAosK9kWbP40LzM91CNQ3$7k/BaFjdP0xqlTcaVCLi7ajFhhXc+syX5mzPYgl/8Ro=	\N	f	nilimaprasad	Nilima	Prasad	nilimaprasad@hotmail.com	f	t	2025-10-13 17:40:36.110949+00
13	pbkdf2_sha256$600000$f2fZOg09h9B9bExPVfaPCr$LG86m47d+DLqLps8mA/81VPs17eJq6dWN5m2/K2mpkU=	\N	f	dayamaibasu	Dayamai	Basu	dayamaibasu@yahoo.in	f	t	2025-10-13 17:40:36.340957+00
14	pbkdf2_sha256$600000$kBALXIeXuwTVuLEqtidjWV$fud4EklJwrb5OHC7ha8gNskGlT8UjSyqNzq6SAtluW8=	\N	f	vedhikadua	Vedhika	Dua	vedhikadua@gmail.com	f	t	2025-10-13 17:40:36.569563+00
15	pbkdf2_sha256$600000$h4bGtOi7SqBAPgmrj70Eb0$AAS3lX1wxTzB25apxNkr7cUmOb2PdOJtWtfQGZAzyV8=	\N	f	chaitalygara	Chaitaly	Gara	chaitalygara@gmail.com	f	t	2025-10-13 17:40:36.798655+00
16	pbkdf2_sha256$600000$yiUowbWi3VbbXZK6TUpwPo$d5fmyrp+Jbl+NFsk4rkKnvTijdl7uSvRGAbVvAo7hMA=	\N	f	triyachand	Triya	Chand	triyachand@hotmail.com	f	t	2025-10-13 17:40:37.017038+00
17	pbkdf2_sha256$600000$MNUSjqzCyL8PeVWFblOC9Y$0urI3J0e6wcq1I2FrTlCuUwvsPW7HumbM0m07/xj6Qg=	\N	f	dhritigolla	Dhriti	Golla	dhritigolla@gmail.com	f	t	2025-10-13 17:40:37.236044+00
18	pbkdf2_sha256$600000$XbwwWsXsFeL6MHYtDq2x7s$cKXyVniTpvpcWOVu/QUEzxMRbOZzNMyxnBu/VVMeSCg=	\N	f	bhavanisavant	Bhavani	Savant	bhavanisavant@gmail.com	f	t	2025-10-13 17:40:37.476422+00
19	pbkdf2_sha256$600000$8K9NF6D9XDdJg6NC5xHtLI$kyAwKhcqpk8wfM++Hno4s/Hmi30J//aSFDTV+/dCd9Q=	\N	f	triyakara	Triya	Kara	triyakara@gmail.com	f	t	2025-10-13 17:40:37.705435+00
20	pbkdf2_sha256$600000$tZH7TBIOfDDvqwzXMRCh01$mXKf4zAhMlZ7daqy7rEnp27dwRF23faKoJJDkwGepSs=	\N	f	tarakbains	Tarak	Bains	tarakbains@gmail.com	f	t	2025-10-13 17:40:37.9352+00
21	pbkdf2_sha256$600000$eulMcMqHTEqle5zYZP74tB$zes3KdkM8kfiSVMnSeaCoIjiGE7iUF4dNbgF9UlhmaI=	\N	f	vinayadeep	Vinaya	Deep	vinayadeep@gmail.com	f	t	2025-10-13 17:40:38.176044+00
22	pbkdf2_sha256$600000$k7CwNtXGJTMyPc1uKXOIYp$VeeLiurFW9JJVZP4rgtU4UxPY02FzPRYM7VgwCWvZy0=	\N	f	williamchoudhry	William	Choudhry	williamchoudhry@outlook.com	f	t	2025-10-13 17:40:38.405121+00
23	pbkdf2_sha256$600000$qURH7UNh2sahFSZNQq4MmD$DA/d7J5mJCtEmeK2Zs8+BaloNNVOAOFHRKA3S9Pa+8g=	\N	f	darpanratti	Darpan	Ratti	darpanratti@yahoo.in	f	t	2025-10-13 17:40:38.676626+00
24	pbkdf2_sha256$600000$kTyZQRYNaDcploPpE0ECfR$YPo9qCR07gpiyMO9G0qfG7E5lbOgEi+3vegICI48g3c=	\N	f	urvashidayal	Urvashi	Dayal	urvashidayal@yahoo.in	f	t	2025-10-13 17:40:38.928849+00
25	pbkdf2_sha256$600000$3iQlN6WOKrks8u1YzxaPvK$DP/6D7JPCPdBMZsRsv1TvMRp2ImWvJBdS767rH7Z174=	\N	f	lopasharma	Lopa	Sharma	lopasharma@outlook.com	f	t	2025-10-13 17:40:39.160599+00
26	pbkdf2_sha256$600000$O2zeNALyikaj9j1BjUMIPs$mNac6Ddg6X6e0424OgiPoKzAHLhNEtQQ5WGNMK9HYbc=	\N	f	vincentsehgal	Vincent	Sehgal	vincentsehgal@hotmail.com	f	t	2025-10-13 17:40:39.479104+00
27	pbkdf2_sha256$600000$Md5Kq6oZ2Llk6iNEN83gTJ$GUqhQayLm/e0I7IhpB/q1p1fg8xob6uJMthYOZCAOcI=	\N	f	michaelpurohit	Michael	Purohit	michaelpurohit@outlook.com	f	t	2025-10-13 17:40:39.719404+00
28	pbkdf2_sha256$600000$3jSCm7qCwFmGwXT2Gf4KPR$kEg7svkxz6/ympvVEFgm168KcI4l5teHpQ3UfURQ+XQ=	\N	f	noahverma	Noah	Verma	noahverma@outlook.com	f	t	2025-10-13 17:40:39.960841+00
29	pbkdf2_sha256$600000$oV4oBcI5LvBLtPkXkkoTzo$SeT13Yomp9xN/IK/42b4npd4cbOW9tmrb/cvXOV+hu0=	\N	f	owenmander	Owen	Mander	owenmander@outlook.com	f	t	2025-10-13 17:40:40.214819+00
30	pbkdf2_sha256$600000$tWwjV3ote8x0thHoAp0Gly$NsS2C65E873MrApoFLQuXckUFwgent6LgF6wraKhqqg=	\N	f	devwalla	Dev	Walla	devwalla@outlook.com	f	t	2025-10-13 17:40:40.454699+00
31	pbkdf2_sha256$600000$KH6S1vnOkfyhI66tawj2CG$wEsofakjI9GcWQEr+Sg9T2s6UGR3zzm275Q4RwDaxYw=	\N	f	hemangchandra	Hemang	Chandra	hemangchandra@outlook.com	f	t	2025-10-13 17:40:40.684783+00
32	pbkdf2_sha256$600000$jLyIOdS4iZmUuLF4dmQPc3$s53MHGDSoqx5vFslFIbFXn6YCDKddc0cNw4nw8cjfYA=	\N	f	kashvibiswas	Kashvi	Biswas	kashvibiswas@hotmail.com	f	t	2025-10-13 17:40:40.925079+00
33	pbkdf2_sha256$600000$pGdQMqk8meCU71jJpmo8kC$P+tiMG527YJDrSLmrT/Fx0OQ+cYhJeqmr1GzH/0ViGw=	\N	f	mananseth	Manan	Seth	mananseth@gmail.com	f	t	2025-10-13 17:40:41.154809+00
34	pbkdf2_sha256$600000$6Z8U265DyEow3ptzaWBCos$T4+fwzUBbb3Z5Pol/ayE+dpYTUCnjDO+wUJVlLxC24M=	\N	f	rishinaik	Rishi	Naik	rishinaik@outlook.com	f	t	2025-10-13 17:40:41.382622+00
35	pbkdf2_sha256$600000$9vU8ZGIGRllsIzS64Uplk2$Yy4rWB+96sU3RPfoTsmQA7u47Fifgq6vti4cWGU+6tg=	\N	f	warhisachdeva	Warhi	Sachdeva	warhisachdeva@hotmail.com	f	t	2025-10-13 17:40:41.602154+00
36	pbkdf2_sha256$600000$5zYnfRvlvo4DOgOOfAGCPh$ESyR4La6cNfhhsBWg1EMXNCx2wJpVE/IkDulN1aOp+E=	\N	f	lilamalhotra	Lila	Malhotra	lilamalhotra@gmail.com	f	t	2025-10-13 17:40:41.842645+00
37	pbkdf2_sha256$600000$pmykxo7SwuRQsPObxKhEEA$liDAlepBQbMCceJ6nxUnVUJRrHnhqf2JfcQZtMHDGlI=	\N	f	bimalapradhan	Bimala	Pradhan	bimalapradhan@gmail.com	f	t	2025-10-13 17:40:42.105815+00
38	pbkdf2_sha256$600000$pFs2L5yEgf08piLpGO6roa$vCAPpwfv/1tDpOzeCk3NU0p44At2CXT6lvz2jMt8g8I=	\N	f	gautamsule	Gautam	Sule	gautamsule@hotmail.com	f	t	2025-10-13 17:40:42.333071+00
39	pbkdf2_sha256$600000$T80fYLRZ16YTkjlmb55SiX$PglUWD7J9hDlIGvYFeqJS2uoan2GN92qFL/gYtfR/Ao=	\N	f	falanvohra	Falan	Vohra	falanvohra@yahoo.in	f	t	2025-10-13 17:40:42.58342+00
40	pbkdf2_sha256$600000$V5fa4gXZSrZAZVtKmDj0kR$GvB6hwwWSIIH+QVZmwnHadzbPNkhgVvFxvhr/aaXixo=	\N	f	akshaypant	Akshay	Pant	akshaypant@hotmail.com	f	t	2025-10-13 17:40:42.807208+00
41	pbkdf2_sha256$600000$R9ekGrCZdBGvdunvRmbVsr$LbJXHumkI2vp9XfNLn9y62QaMJsZf7ncYZpQUmfjpzo=	\N	f	udarshrao	Udarsh	Rao	udarshrao@hotmail.com	f	t	2025-10-13 17:40:43.036046+00
42	pbkdf2_sha256$600000$rgbpunnsFblbzxsBszkdng$RL9vyIgdYxlUFeuC1tSp6dOgw7xzPFlhgYmci6HhwsE=	\N	f	vasanabhavsar	Vasana	Bhavsar	vasanabhavsar@gmail.com	f	t	2025-10-13 17:40:43.254876+00
43	pbkdf2_sha256$600000$cirZVSJXtXRfRU8bCWQprM$LHAwp5V9WlUVkHRm9JhDZMUck60TtoYE8K/hefxK9wc=	\N	f	girindracomar	Girindra	Comar	girindracomar@outlook.com	f	t	2025-10-13 17:40:43.481914+00
44	pbkdf2_sha256$600000$bv1Gbgc9QBVeMYJjXbxEbt$ldPeaDGjxQGmTHgLEYKJqIRDSqDv8Q160aH9QLFQ9eI=	\N	f	chakrikaborde	Chakrika	Borde	chakrikaborde@yahoo.in	f	t	2025-10-13 17:40:43.703154+00
45	pbkdf2_sha256$600000$MEMkZFipBg8hkRbPC08dQr$h52zvF9BKC/jy1d+X3bGv+np+RFm2siJy9FdF3k5ebQ=	\N	f	adityasastry	Aditya	Sastry	adityasastry@hotmail.com	f	t	2025-10-13 17:40:43.931465+00
46	pbkdf2_sha256$600000$caWnBTV4msgbvo5ZNFjndX$sacXnm+adFbKYsidG1zVwLZsMiC85QurZ7tstSWKcuY=	\N	f	teerthbansal	Teerth	Bansal	teerthbansal@hotmail.com	f	t	2025-10-13 17:40:44.15104+00
47	pbkdf2_sha256$600000$1pZLUxYKW45M0LswPeCT31$0kfB6QBbHJRMo5DhSi7b4958XWXeg6NSAuCE450vUQg=	\N	f	chakrikamani	Chakrika	Mani	chakrikamani@yahoo.in	f	t	2025-10-13 17:40:44.379218+00
48	pbkdf2_sha256$600000$wzE9fXPN9uN8wlFnXw6U6Q$ny08ktMrb//UjnE+4f+Huet58FWEMTP8NaNst8Py3RQ=	\N	f	raaginichopra	Raagini	Chopra	raaginichopra@gmail.com	f	t	2025-10-13 17:40:44.598115+00
49	pbkdf2_sha256$600000$cxfqluGRAaRksBtC8f7CUe$gz8U1kpOsjRgYXFUlJuNuDlWrSZiuh+0DVhqYjmwL3A=	\N	f	masonvohra	Mason	Vohra	masonvohra@outlook.com	f	t	2025-10-13 17:40:44.827211+00
50	pbkdf2_sha256$600000$ex26feiMI8xk94MIymtMci$w3IqBkuKLwuju40oaPX8UQK5FEHzluEK3evyuOhav0E=	\N	f	ridhigarg	Ridhi	Garg	ridhigarg@gmail.com	f	t	2025-10-13 17:40:45.056576+00
51	pbkdf2_sha256$600000$3Ja74QNzIxP3pK8TMUYqcm$Ql8oJ1/oknfdywUtNQ9xNUYIkiOYpPT1Mwb6lVJRmxw=	\N	f	hamsinivenkatesh	Hamsini	Venkatesh	hamsinivenkatesh@outlook.com	f	t	2025-10-13 17:40:45.286505+00
52	pbkdf2_sha256$600000$8klE79IOLrSMDA6P6lx50f$9dmwTyzNNtUT1a8iiDxgcEii11MTQA3EKyIiIxhDbvM=	\N	f	samuelkant	Samuel	Kant	samuelkant@gmail.com	f	t	2025-10-13 17:40:45.516133+00
53	pbkdf2_sha256$600000$KcmBLg74v7U4LDvXIBdRab$71Rf9rWfMU5cuFF+t9egdwiQ0RXPsr9w+b2Z1ONFRug=	\N	f	qadimbains	Qadim	Bains	qadimbains@gmail.com	f	t	2025-10-13 17:40:45.733291+00
54	pbkdf2_sha256$600000$G0xQcsc4HaKa2zV8er18sa$ILU8W/TnSfj91BHE622eV/4m1wwav5e24cHRoNJh4uM=	\N	f	turviroy	Turvi	Roy	turviroy@hotmail.com	f	t	2025-10-13 17:40:45.964958+00
55	pbkdf2_sha256$600000$8GTTXszuK2e7mGLj0XbFiJ$GH6/wosOXHN7L2QEcdJXh+WRN1qQQUNV7NbqjxjmdgA=	\N	f	hemakakar	Hema	Kakar	hemakakar@yahoo.in	f	t	2025-10-13 17:40:46.192477+00
56	pbkdf2_sha256$600000$VQm504dyHjn4DoM9ftb9dN$YVfoDQ5aoyjWBvL48yahYJY3ZCWAxp8qPRyr5u+Z2vI=	\N	f	chakradevdave	Chakradev	Dave	chakradevdave@hotmail.com	f	t	2025-10-13 17:40:46.41094+00
57	pbkdf2_sha256$600000$qUXLnQ4lZGDmHUBcaK2Gvm$TQEOphtyhhU03jVmoJ9OsQzUm5j2ktAENI+uLcXYdLU=	\N	f	gautamkrish	Gautam	Krish	gautamkrish@hotmail.com	f	t	2025-10-13 17:40:46.629001+00
58	pbkdf2_sha256$600000$BBRJgl0nwcOnfgs4mxKd6s$qNW85YbupILeE5OTmnWy03O65xWTR7W/KR67QeFuSRM=	\N	f	aayushchana	Aayush	Chana	aayushchana@hotmail.com	f	t	2025-10-13 17:40:46.859109+00
59	pbkdf2_sha256$600000$Ivta2eSdGLnIHsHpufo3J6$7FJTPPPhYfjkHieLfVPC/FFnGsF6oZCDUTV0Rs9I6Ts=	\N	f	harrisontalwar	Harrison	Talwar	harrisontalwar@yahoo.in	f	t	2025-10-13 17:40:47.087924+00
60	pbkdf2_sha256$600000$JhcNiIttCVVLXaqoBGpwGA$t3Pf9v088RsPoscB8kAbHv+z5jY/6KOA/bFkYFn0Nv8=	\N	f	anmolpatel	Anmol	Patel	anmolpatel@hotmail.com	f	t	2025-10-13 17:40:47.437278+00
61	pbkdf2_sha256$600000$DeVbjDDTsV6PHfqCIV1i2h$kGWbaXfJMcY4ryiE79foAo61Z553RBRnrLJxZPAmhJo=	\N	f	zarnanazareth	Zarna	Nazareth	zarnanazareth@gmail.com	f	t	2025-10-13 17:40:47.717104+00
62	pbkdf2_sha256$600000$p1eq2UWG3dANnuUPGquzXP$rjWMPUgzAKrZYJx6zM5tOBaXEFKraQSYJpn+oHkYoPM=	\N	f	veerdalia	Veer	D’Alia	veerdalia@yahoo.in	f	t	2025-10-13 17:40:47.947759+00
63	pbkdf2_sha256$600000$x7f1OGSy6fDMJhthRGoUYZ$/SkGoFrt8wJlwQijHBmkPcvE2BRKjMxqh/4N2y0XIS4=	\N	f	shauryasur	Shaurya	Sur	shauryasur@yahoo.in	f	t	2025-10-13 17:40:48.164615+00
64	pbkdf2_sha256$600000$NoObYzqZ9jbg60CIzKmMbI$CvDqluEd4jmA5O1I9himg8T5NXSxnq4YMcAATDXH3vM=	\N	f	tejaskhare	Tejas	Khare	tejaskhare@gmail.com	f	t	2025-10-13 17:40:48.394227+00
65	pbkdf2_sha256$600000$xYrPDzfOc4QxULyWJ1aXJ9$pIzUzqttVDyLgMStMGlgoOblpUfQUpp+1de1eOhhwrc=	\N	f	ekanshtandon	Ekansh	Tandon	ekanshtandon@outlook.com	f	t	2025-10-13 17:40:48.623637+00
66	pbkdf2_sha256$600000$9btkwJ47Iloa4hmdyFB2M3$/a98Sdq1Q/VJbuhSACz1PVUUmhwknYdZtZfh+wTmn88=	\N	f	ishaannagi	Ishaan	Nagi	ishaannagi@outlook.com	f	t	2025-10-13 17:40:48.84204+00
67	pbkdf2_sha256$600000$bmA5lnlPxLd4Hoe6sHMMb7$mc66myJYJ30MtEshkgAuMyVw8yhVU+pm4Sj+8XSCpVg=	\N	f	upadhritikanda	Upadhriti	Kanda	upadhritikanda@gmail.com	f	t	2025-10-13 17:40:49.082176+00
68	pbkdf2_sha256$600000$pqLgwJg0wCLDZy5Gpwivkb$qXyIysNyYMuIT0niuFFymmHuP1gskAXuh0KQT9Ivlik=	\N	f	balveerhari	Balveer	Hari	balveerhari@yahoo.in	f	t	2025-10-13 17:40:49.357101+00
69	pbkdf2_sha256$600000$2t3Y9AicKn0GpJDnyJ8dcO$y+5b7KwY9BAzGn2Ic6QV8P7/4ju+Y4jP7E8ZOccDSoo=	\N	f	tanmayisahota	Tanmayi	Sahota	tanmayisahota@outlook.com	f	t	2025-10-13 17:40:49.585716+00
70	pbkdf2_sha256$600000$DmU01lkNRjISjGjs9Ul2T3$yJ1XAZEaShvF5eU/Pc5eA7IeQaPC0C3QAF/yUYx0B28=	\N	f	qushikakar	Qushi	Kakar	qushikakar@hotmail.com	f	t	2025-10-13 17:40:49.815107+00
71	pbkdf2_sha256$600000$zZubiC5c3qICq4XqCeHFEQ$BPxsAW4SORdXjpvEy32Ge3vLong1ELJs8JvwOdO4s1g=	\N	f	farajchadha	Faraj	Chadha	farajchadha@outlook.com	f	t	2025-10-13 17:40:50.044874+00
72	pbkdf2_sha256$600000$W2JjJ0uSwQRbRoAAkrbInx$fUewyAO8D8LyMFTtly9Kvqf35fF09DFeymfm7QDpFCs=	\N	f	samakshnaik	Samaksh	Naik	samakshnaik@yahoo.in	f	t	2025-10-13 17:40:50.29719+00
73	pbkdf2_sha256$600000$4kDjPgluH7DaL3A89Vo03u$Eb7PyIWPEX8UR/lojsUjy1Iw/iZURZxzsQps9lrVMus=	\N	f	ucchalbanerjee	Ucchal	Banerjee	ucchalbanerjee@gmail.com	f	t	2025-10-13 17:40:50.524624+00
74	pbkdf2_sha256$600000$vjYx6Vp9kQKlQPYpQHlcUj$ZSExWY/r9BR3+WzzyW5OVNaM8xaOZc8S0WgJIfDMXqQ=	\N	f	raghavbala	Raghav	Bala	raghavbala@gmail.com	f	t	2025-10-13 17:40:50.809079+00
75	pbkdf2_sha256$600000$Eci87DCsJthNvVdQ58UU2n$7VAeeu4LcvqxwfShF871VxgIrhOne2NEcB6ZdH6T7fw=	\N	f	anvibumb	Anvi	Bumb	anvibumb@hotmail.com	f	t	2025-10-13 17:40:51.040133+00
76	pbkdf2_sha256$600000$imEQDmsbuEKleG5aCBY6En$XMxml89iLahL3iOd8u1X6Kny8i7ACCi5iDqIK8KaWH0=	\N	f	aarushjayaraman	Aarush	Jayaraman	aarushjayaraman@outlook.com	f	t	2025-10-13 17:40:51.269499+00
77	pbkdf2_sha256$600000$kaZ9AEyIEyRaJCArF6uQua$TqmDZs2J70sC+CzyyeF+uaHwVEXqx+jAtqj6UaQt5hg=	\N	f	arjunmerchant	Arjun	Merchant	arjunmerchant@outlook.com	f	t	2025-10-13 17:40:51.497028+00
78	pbkdf2_sha256$600000$0WGcLXCtYXOWnLb77XQt3Z$0Yw+SwQf/AoLr1Q3qTknSagjZO3AkB0hKt3e1bGGARQ=	\N	f	maanasghose	Maanas	Ghose	maanasghose@gmail.com	f	t	2025-10-13 17:40:51.750237+00
79	pbkdf2_sha256$600000$tYVZhQpLPmFvf2PK9VHsvi$QECU/gKhYm4AHFk6tyZg3jxnJY9GPi59Cp3XJ8aoZCM=	\N	f	saivarkey	Sai	Varkey	saivarkey@gmail.com	f	t	2025-10-13 17:40:52.123667+00
80	pbkdf2_sha256$600000$sihaaTew2bfHeG6muXV9is$QhN70a3sW/kxju153A8zs43zdlr21a5YZRvPPueI45U=	\N	f	matthewkhosla	Matthew	Khosla	matthewkhosla@hotmail.com	f	t	2025-10-13 17:40:52.501132+00
81	pbkdf2_sha256$600000$6NnCVJrkUUBQmc3Z9uHP6f$6GWCEcA5QcxUl+X+y2Hz5kFT/qP6RPrZZymRYJMRZUw=	\N	f	indrajitnagi	Indrajit	Nagi	indrajitnagi@outlook.com	f	t	2025-10-13 17:40:52.756203+00
82	pbkdf2_sha256$600000$REiqsa2sfExF9BBjd1iUcf$qhWiC5OngRdHa9NbYxD3bKjufHHHSwXSvBzIhlTpXY8=	\N	f	tristanbrahmbhatt	Tristan	Brahmbhatt	tristanbrahmbhatt@outlook.com	f	t	2025-10-13 17:40:52.984752+00
83	pbkdf2_sha256$600000$ACUyhI97BoAt2Pqmb6Q8oL$wiFaHmmYb98H1wRh6I5OcImz93zaT72O+BxyibbQsFQ=	\N	f	vasudhapatla	Vasudha	Patla	vasudhapatla@hotmail.com	f	t	2025-10-13 17:40:53.213522+00
84	pbkdf2_sha256$600000$AlJLBVHwf6SXnpdqYDTOoZ$/jygXteYs7ynHjmqVjYj4B3XM80MPzTgspsAKLeagYQ=	\N	f	yaminisaraf	Yamini	Saraf	yaminisaraf@gmail.com	f	t	2025-10-13 17:40:53.443315+00
85	pbkdf2_sha256$600000$T98URrFGjTfDTuC1PU9Oek$m8lYenSFC1r+rk3ORjdbixZF0UCN0fl/olSdy5uLgJE=	\N	f	wakeetanath	Wakeeta	Nath	wakeetanath@yahoo.in	f	t	2025-10-13 17:40:53.672484+00
86	pbkdf2_sha256$600000$2RaZWYQAveQQDShmpRa1Y6$UCjgAmq0bUiN0t/j6wAu8qlsCNm11qo2L7Od24756T4=	\N	f	benjaminbarad	Benjamin	Barad	benjaminbarad@hotmail.com	f	t	2025-10-13 17:40:53.902373+00
87	pbkdf2_sha256$600000$7wHJlBT5XbG0diPTkfmSVK$IjgzBUcikRnWGzwwnadCHj9fxRrAQynKZ20gOI37gvw=	\N	f	dakshaboase	Daksha	Boase	dakshaboase@gmail.com	f	t	2025-10-13 17:40:54.131681+00
88	pbkdf2_sha256$600000$vCzVzaQfU8W6uDbnFgFLkc$UDfOZJs5ih/449Tva9e1NaLoHjFLqu8wYh0WCcRLqF4=	\N	f	onveermerchant	Onveer	Merchant	onveermerchant@gmail.com	f	t	2025-10-13 17:40:54.372512+00
89	pbkdf2_sha256$600000$RNYtmkcWyRUi7L1KPdRrxx$laH6VAtaS+Ja7+TWayKcb7R5oWTmgm/0UBHvis5g0fE=	\N	f	aayushdate	Aayush	Date	aayushdate@yahoo.in	f	t	2025-10-13 17:40:54.602005+00
90	pbkdf2_sha256$600000$o2lB1FX5qpTnX2HbEmPssp$dTYhgNuo59gyu0jtFx8Ac3XVDG2J0JMRuWSaMg643nU=	\N	f	meerapingle	Meera	Pingle	meerapingle@gmail.com	f	t	2025-10-13 17:40:54.820152+00
91	pbkdf2_sha256$600000$1n4R8iArRM7jKRTsAzu2vW$ni1Ki3x87RztjMtsHwvyFBfAs1lqhZJXT7221pf3FDo=	\N	f	kalalad	Kala	Lad	kalalad@outlook.com	f	t	2025-10-13 17:40:55.078339+00
92	pbkdf2_sha256$600000$Qaad21McDv9DJT7BXv560I$tBf3B8vuIvRxrXr1CkviK2cIB4zAxBvVJMKn2hbJsAY=	\N	f	ethanbalasubramanian	Ethan	Balasubramanian	ethanbalasubramanian@gmail.com	f	t	2025-10-13 17:40:55.373702+00
93	pbkdf2_sha256$600000$MaSj8Tli1Ktlbvyv7yN6iw$jGrcM8E4xbvl5WGpXuggQoIt5vTM//CRnk4Q6fipPj8=	\N	f	chaitanyabawa	Chaitanya	Bawa	chaitanyabawa@outlook.com	f	t	2025-10-13 17:40:55.602759+00
94	pbkdf2_sha256$600000$bgp3XyzpphchgONdYbpiLd$t+iFmcYKvxp95MMEyJ5TpZblZ1xojKNc5/AoA7Jrf/Y=	\N	f	qabilchhabra	Qabil	Chhabra	qabilchhabra@yahoo.in	f	t	2025-10-13 17:40:55.910531+00
95	pbkdf2_sha256$600000$OGT0y5ZDdEfQxcut24GYKL$K3kFUyBgA3XDPya8DysOU7dcfQuQHTHCharlB3AAs/I=	\N	f	dhruvgera	Dhruv	Gera	dhruvgera@hotmail.com	f	t	2025-10-13 17:40:56.15065+00
96	pbkdf2_sha256$600000$RrNkh7SWtoAM1x9TA4CoXd$v3t6/lWW3F3DEsPpdA4lMOokLczhyGBCZXli0gxBc2g=	\N	f	ekalingatoor	Ekalinga	Toor	ekalingatoor@hotmail.com	f	t	2025-10-13 17:40:56.36889+00
97	pbkdf2_sha256$600000$OrQPOU8CWtHoPYXakJIPC0$zNjCVPMyA7lXPueaVIS1+3WQA/XTVccJ8lkfOpPz2zo=	\N	f	dhruvtailor	Dhruv	Tailor	dhruvtailor@yahoo.in	f	t	2025-10-13 17:40:56.591861+00
98	pbkdf2_sha256$600000$NWuWG07QlKaBegfoHciqqJ$i7sdveXc1ivLgGjizsQgpf1wymYTbpdU3Ekb+HY9gn8=	\N	f	deepamunshi	Deepa	Munshi	deepamunshi@yahoo.in	f	t	2025-10-13 17:40:56.821516+00
99	pbkdf2_sha256$600000$Pp8FmiKFeHKsaJFPq417nc$k6v4jaPJr5lllEujlLwpsukEZdRpnqnasrkMSrvvBfo=	\N	f	ekantikababu	Ekantika	Babu	ekantikababu@yahoo.in	f	t	2025-10-13 17:40:57.05103+00
100	pbkdf2_sha256$600000$1iPFvOHhYcWuqRGY3RSoBM$nu6KobwBGIZIJ2RHaeaUZYwND4Qv9DzUHlMjyblkUKI=	\N	f	ishaupadhyay	Isha	Upadhyay	ishaupadhyay@gmail.com	f	t	2025-10-13 17:40:57.280725+00
101	pbkdf2_sha256$600000$s5P7RyGt8qdcGGxmXz63mo$j6FTuTnJPlv1aCeppCy2QNO26l62qcpkLsE+u1qj2jo=	\N	f	qushipatla	Qushi	Patla	qushipatla@hotmail.com	f	t	2025-10-13 17:40:57.509913+00
102	pbkdf2_sha256$600000$95M2256YqMBEYXWYtqErnk$SMAqfOXnEINtf+73WsUAz86DleDBN2hbPwNou+Cu/xs=	\N	f	dhruvdhillon	Dhruv	Dhillon	dhruvdhillon@outlook.com	f	t	2025-10-13 17:40:57.764519+00
103	pbkdf2_sha256$600000$DHoeySk6TbCqee2SjoIfq4$vbRayxpbnd/8gFKI50JPZjj9B7O6tzl1g5A4eb5pBC8=	\N	f	kritikakrish	Kritika	Krish	kritikakrish@hotmail.com	f	t	2025-10-13 17:40:57.994025+00
104	pbkdf2_sha256$600000$06tLpu6xcxFQnGxbU26Dre$xqpceKOyk7tSihxKX56oGFfjJZshRBCM7/9RsOG/psI=	\N	f	mohininarasimhan	Mohini	Narasimhan	mohininarasimhan@outlook.com	f	t	2025-10-13 17:40:58.223486+00
105	pbkdf2_sha256$600000$4dofMrPnRun70cHav36i3d$BOZo93mCmiwLFxNjZMSxDRddgPEbicgK1Fybueq+Rgo=	\N	f	libnikannan	Libni	Kannan	libnikannan@yahoo.in	f	t	2025-10-13 17:40:58.45306+00
106	pbkdf2_sha256$600000$CQJg4wDGXFYsks5NyIDyqu$m1nmz1f7qOzX8GvtiyE+bru7jkzY07G1MjwzvKZPZ4Y=	\N	f	aachalnadkarni	Aachal	Nadkarni	aachalnadkarni@gmail.com	f	t	2025-10-13 17:40:58.681719+00
107	pbkdf2_sha256$600000$8fI5lmedyhNgh4laH6bnxz$29DG6xgrbRcU9JNv0cocKq8tfR/nAfiYxEVprHLa7P0=	\N	f	harinigoel	Harini	Goel	harinigoel@outlook.com	f	t	2025-10-13 17:40:58.90017+00
108	pbkdf2_sha256$600000$GOPxrohvC00VVA9MTOhFLY$qJiACtbQoQsA62SvHgjXiL0ci/FgHKT592ZnkU8SqZM=	\N	f	yauvanikrishnamurthy	Yauvani	Krishnamurthy	yauvanikrishnamurthy@hotmail.com	f	t	2025-10-13 17:40:59.129844+00
109	pbkdf2_sha256$600000$NJraXhUmfXn6541AwHgav2$C79hOGhsw4k0yd295mHkZkd3uirNLOuKZ2t5UV62grE=	\N	f	sanyasubramanian	Sanya	Subramanian	sanyasubramanian@yahoo.in	f	t	2025-10-13 17:40:59.359813+00
110	pbkdf2_sha256$600000$MJ0aZzBy3jfbehyhNkxil2$dS3B35Dq3imEsuDvJZfmS7Iwg/9Gah7ikkUqi6BR9gg=	\N	f	radhashanker	Radha	Shanker	radhashanker@gmail.com	f	t	2025-10-13 17:40:59.597544+00
111	pbkdf2_sha256$600000$jawiHvCAKFAhf7QnBANvvM$zZ2YwwzDS6q4z557oDdx/crpNy/zFW1ZD6mnibMqsGY=	\N	f	hredhaanvarma	Hredhaan	Varma	hredhaanvarma@yahoo.in	f	t	2025-10-13 17:40:59.81793+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
1	2	1
2	3	1
3	4	1
4	5	1
5	6	1
6	7	1
7	8	1
8	9	1
9	10	1
10	11	1
11	12	2
12	13	2
13	14	2
14	15	2
15	16	2
16	17	2
17	18	2
18	19	2
19	20	2
20	21	2
21	22	2
22	23	2
23	24	2
24	25	2
25	26	2
26	27	2
27	28	2
28	29	2
29	30	2
30	31	2
31	32	2
32	33	2
33	34	2
34	35	2
35	36	2
36	37	2
37	38	2
38	39	2
39	40	2
40	41	2
41	42	2
42	43	2
43	44	2
44	45	2
45	46	2
46	47	2
47	48	2
48	49	2
49	50	2
50	51	2
51	52	2
52	53	2
53	54	2
54	55	2
55	56	2
56	57	2
57	58	2
58	59	2
59	60	2
60	61	2
61	62	2
62	63	2
63	64	2
64	65	2
65	66	2
66	67	2
67	68	2
68	69	2
69	70	2
70	71	2
71	72	2
72	73	2
73	74	2
74	75	2
75	76	2
76	77	2
77	78	2
78	79	2
79	80	2
80	81	2
81	82	2
82	83	2
83	84	2
84	85	2
85	86	2
86	87	2
87	88	2
88	89	2
89	90	2
90	91	2
91	92	2
92	93	2
93	94	2
94	95	2
95	96	2
96	97	2
97	98	2
98	99	2
99	100	2
100	101	2
101	102	2
102	103	2
103	104	2
104	105	2
105	106	2
106	107	2
107	108	2
108	109	2
109	110	2
110	111	2
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-10-13 16:57:07.708735+00	10	Intro to Econometrics	2	[{"changed": {"name": "lesson", "object": "Data types & sources", "fields": ["Position"]}}, {"changed": {"name": "lesson", "object": "Statistical foundations", "fields": ["Position"]}}, {"changed": {"name": "lesson", "object": "Simple linear regression", "fields": ["Position"]}}, {"changed": {"name": "lesson", "object": "Multiple regression", "fields": ["Position"]}}, {"changed": {"name": "lesson", "object": "Hypothesis testing", "fields": ["Position"]}}, {"changed": {"name": "lesson", "object": "Model specification", "fields": ["Position"]}}, {"changed": {"name": "lesson", "object": "Heteroskedasticity & remedies", "fields": ["Position"]}}, {"changed": {"name": "lesson", "object": "Instrumental variables (intro)", "fields": ["Position"]}}, {"changed": {"name": "lesson", "object": "Panel data basics", "fields": ["Position"]}}, {"changed": {"name": "lesson", "object": "Interpreting results", "fields": ["Position"]}}]	7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	contenttypes	contenttype
2	admin	logentry
3	auth	permission
4	auth	group
5	auth	user
6	sessions	session
7	academics	course
8	academics	lesson
9	academics	lessonchecklistitem
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-10-07 14:50:20.421767+00
2	auth	0001_initial	2025-10-07 14:50:23.618881+00
3	academics	0001_initial	2025-10-07 14:50:24.822872+00
4	academics	0002_historicallessonchecklistitem_historicallesson_and_more	2025-10-07 14:50:27.209346+00
5	academics	0003_historicaluser_historicalgroup	2025-10-07 14:50:29.326398+00
6	academics	0004_remove_historicalgroup_history_user_and_more	2025-10-07 14:50:29.431247+00
7	admin	0001_initial	2025-10-07 14:50:30.019622+00
8	admin	0002_logentry_remove_auto_add	2025-10-07 14:50:30.06388+00
9	admin	0003_logentry_add_action_flag_choices	2025-10-07 14:50:30.097434+00
10	contenttypes	0002_remove_content_type_name	2025-10-07 14:50:30.14599+00
11	auth	0002_alter_permission_name_max_length	2025-10-07 14:50:30.178786+00
12	auth	0003_alter_user_email_max_length	2025-10-07 14:50:30.213145+00
13	auth	0004_alter_user_username_opts	2025-10-07 14:50:30.252697+00
14	auth	0005_alter_user_last_login_null	2025-10-07 14:50:30.285661+00
15	auth	0006_require_contenttypes_0002	2025-10-07 14:50:30.315235+00
16	auth	0007_alter_validators_add_error_messages	2025-10-07 14:50:30.351096+00
17	auth	0008_alter_user_username_max_length	2025-10-07 14:50:30.525108+00
18	auth	0009_alter_user_last_name_max_length	2025-10-07 14:50:30.55897+00
19	auth	0010_alter_group_name_max_length	2025-10-07 14:50:30.597058+00
20	auth	0011_update_proxy_permissions	2025-10-07 14:50:30.644636+00
21	auth	0012_alter_user_first_name_max_length	2025-10-07 14:50:30.692906+00
22	sessions	0001_initial	2025-10-07 14:50:31.337271+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: scms_admin
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
zi2qhkbpy3kzcpyj4htth2a7t19rmrfr	.eJxVjMsOwiAQRf-FtSHAYAdcuu83kBkeUjU0Ke3K-O_apAvd3nPOfYlA21rD1vMSpiQuQovT78YUH7ntIN2p3WYZ57YuE8tdkQftcpxTfl4P9--gUq_fuvgCXtlSBjSOnUdrAcCzBTznFBOTIkDPClTRBpUbStaMnrKBpBWK9wfPSTdN:1v8LH2:wai1JTVQyH7ew-mNl1XCG0hMTBOrmbgwI7_bVvXszaM	2025-10-27 16:19:48.092355+00
\.


--
-- Name: academics_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.academics_course_id_seq', 10, true);


--
-- Name: academics_lesson_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.academics_lesson_id_seq', 100, true);


--
-- Name: academics_lessonchecklistitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.academics_lessonchecklistitem_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 2, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 36, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 110, true);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 111, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 9, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scms_admin
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- Name: academics_course academics_course_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.academics_course
    ADD CONSTRAINT academics_course_pkey PRIMARY KEY (id);


--
-- Name: academics_lesson academics_lesson_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.academics_lesson
    ADD CONSTRAINT academics_lesson_pkey PRIMARY KEY (id);


--
-- Name: academics_lessonchecklistitem academics_lessonchecklistitem_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.academics_lessonchecklistitem
    ADD CONSTRAINT academics_lessonchecklistitem_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: academics_lesson_course_id_f335c036; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX academics_lesson_course_id_f335c036 ON public.academics_lesson USING btree (course_id);


--
-- Name: academics_lessonchecklistitem_lesson_id_1f580d6a; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX academics_lessonchecklistitem_lesson_id_1f580d6a ON public.academics_lessonchecklistitem USING btree (lesson_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: scms_admin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: academics_lesson academics_lesson_course_id_f335c036_fk_academics_course_id; Type: FK CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.academics_lesson
    ADD CONSTRAINT academics_lesson_course_id_f335c036_fk_academics_course_id FOREIGN KEY (course_id) REFERENCES public.academics_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: academics_lessonchecklistitem academics_lessonchec_lesson_id_1f580d6a_fk_academics; Type: FK CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.academics_lessonchecklistitem
    ADD CONSTRAINT academics_lessonchec_lesson_id_1f580d6a_fk_academics FOREIGN KEY (lesson_id) REFERENCES public.academics_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: scms_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict x1srOOsoRp1pLiQZys4tHhjvHV6PzCXH1qXKTYoBWnVvctt0FHb62yEiVhzqFml

