services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: scms_db
      POSTGRES_USER: scms_admin
      POSTGRES_PASSWORD: admin.123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment: []

volumes:
  postgres_data:
