services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: scms_db
      POSTGRES_USER: scms_admin
      POSTGRES_PASSWORD: admin.123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_NAME: scms_db
      DATABASE_USER: scms_admin
      DATABASE_PASSWORD: admin.123
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      EMAIL_HOST_USER: sahilnayak2056@gmail.com
      EMAIL_HOST_PASSWORD: qncmoohopmitlpiu
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    restart: unless-stopped

  celery-worker:
    build: .
    command: celery -A config worker -l info
    depends_on:
      - db
      - redis
      - web
    environment:
      DATABASE_NAME: scms_db
      DATABASE_USER: scms_admin
      DATABASE_PASSWORD: admin.123
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      EMAIL_HOST_USER: sahilnayak2056@gmail.com
      EMAIL_HOST_PASSWORD: qncmoohopmitlpiu
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
      - redis
      - web
    environment:
      DATABASE_NAME: scms_db
      DATABASE_USER: scms_admin
      DATABASE_PASSWORD: admin.123
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      EMAIL_HOST_USER: sahilnayak2056@gmail.com
      EMAIL_HOST_PASSWORD: qncmoohopmitlpiu
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    restart: unless-stopped

volumes:
  postgres_data:
