# Generated by Django 4.2 on 2025-10-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_historicaluser_historicalgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgroup',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicallesson',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallessonchecklistitem',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallessonchecklistitem',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCourse',
        ),
        migrations.DeleteModel(
            name='HistoricalGroup',
        ),
        migrations.DeleteModel(
            name='HistoricalLesson',
        ),
        migrations.DeleteModel(
            name='HistoricalLessonChecklistItem',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
