# Generated by Django 4.2 on 2025-11-30 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0004_remove_historicalgroup_history_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignedProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academics.course',),
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonchecklistitem',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Lesson Checklist', 'verbose_name_plural': 'Lesson Checklists'},
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Scheduled Date'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'ordering': ('-enrolled_at',),
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academics.enrollment',),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', through='academics.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='academics.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
                'ordering': ['lesson__position'],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
